=== mlombas/SEW_extra/xml/imagen.dtd
<!ELEMENT imagen (
	nombre, descripcion, lugar,
	fecha, posicion?, autor?, licencia?
)>

<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT lugar (coordenadas, region?)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT region ((nombre | id), region?)>

<!ELEMENT fecha (timestamp | iso)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT iso (#PCDATA)>

<!ELEMENT posicion (#PCDATA)>
<!ATTLIST posicion direccion CDATA #REQUIRED>

<!ELEMENT autor (nombre?, email?, telefono?, direccion?)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!ELEMENT licencia (#PCDATA)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT id (#PCDATA)>

=== mlombas/SEW_extra/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagen SYSTEM "imagen.dtd">
<imagen>
	<fotografia>
		https://i.stack.imgur.com/2Sb2P.png
	</fotografia>
	<descripcion>
		Ejemplo de codigo php
	</descripcion>
	<lugar>
		<coordenadas>30.234 32.234</coordenadas>
		<region>
			<nombre>Espa√±a</nombre>
			<region>
				<id>2</id>
			</region>
		</region>
	</lugar>
	<fecha>
		<timestamp>1654788132</timestamp>
	</fecha>
	<posicion direccion="10 10 10">
		En frente del ordenador
	</posicion>
	<autor>
		<nombre>Omar montes</nombre>
		<email>donomar@gmail.com</email>
		<telefono>420 69 69 69</telefono>
		<direccion>Puerto rico</direccion>
	</autor>
	<licencia>MIT</licencia>
</imagen>

=== mlombas/SEW_extra/xml/ejemplo/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagen SYSTEM "imagen.dtd">
<imagen 
	xsi:schemaLocation="imagen.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.uniovi.es"
	>
	<nombre>Glaciar</nombre>
	<descripcion>
		Glaciar en la antártida
	</descripcion>
	<lugar>
		<coordenadas>-81.48459347598022, 158.01761511549236</coordenadas>
		<region>
			<nombre>Antártida</nombre>
			<region>
				<id>1</id>
			</region>
		</region>
	</lugar>
	<fecha>
		<timestamp>1560981600</timestamp>
	</fecha>
	<autor>
		<nombre>Juan Gutierrez</nombre>
		<email>juang@gmail.com</email>
		<telefono>667 10 10 10</telefono>
	</autor>
	<licencia>GNU</licencia>
</imagen>
